# Generated by Django 3.2.18 on 2023-03-29 18:12
import os
import phonenumbers


from django.db import migrations


COUNTRY = os.environ['PHONENUMBER_DEFAULT_REGION']

def set_owner_pure_phone(apps, schema_editor):
    ' Setting owner pure phone '

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator(100):
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, COUNTRY)
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumber
        else:
            flat.owner_pure_phone = None
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator(100):
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230329_2056'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone, move_backward)
    ]
